#+title:  Design
#+author: William Emfinger
#+date:   <2022-04-10 Sun>

* Overall Design
** World
The world within the game is separated into sections of differing scale:
*** Overworld
The largest scale map (hence only the largest scale features show, and the
characters within the map are the smallest scale). The overworld scale is
approximately such that the characters are only 3 blocks tall. The overworld is
also potentially unbounded - meaning at this scale the player can go anywhere
and it is not a fixed camera. While travelling around the overworld, the player
may find places (towns, caves, points of interest) which can be entered - then
taking the player into a fixed local map of lower scale (smaller scale features
show).
*** Local Map
The local map consists of a subset of the map, with bounded extents and in which
the player character is approximately double the size (5-8 blocks tall). Within
this map, the player may find places (houses, cave rooms, etc.) which can be
entered - then taking the player into a fixed interior map of lower scale
(smaller scale features show).
*** Interiors
The interior map is the smallest scale map (smallest features show) and is
reserved for when the player needs to interact with / see very fine features. It
usually represents the interior of houses, cave rooms, and potentially very
specific points of interest within a map (e.g. under a bridge).
** NPCs
All NPCs have some basic characteristics, stats, and behaviors:
- Goal points with path planning
- Health, Stamina, Fear, Magic, Status(es)
- Item & Environment interaction
- Equipment / items / Droppables
- Interaction with other NPCs and player character
- Possessable: they can be controllable by other characters / players
NPCs can come in a variety of types with different customizations between them:
*** Animals
Animals are NPCs which randomly wander around, may forage for food, can be
killed for food, and can be frightened (by player or other NPCs). They can
additionally be interacted with by the player in various ways (e.g. feeding,
petting, etc.)
*** Friendlies
*** Foes
*** Neutrals
** Items
*** Interactible (chests, doors, etc.)
*** Foragable (mushrooms, plants, rocks, etc.)
*** Droppable (health, meat, weapons, armor, etc.)
*** Holdable (weapons, torches, etc.)
** Status Effects
*** In-world / Area of Effects (weather, spell, etc.)
*** Applied (buff, drain, etc.)
